### ISSUE TITLE
Compose 기본사항 #4. 첫 번째 Compose 앱 만들기

### ISSUE THREAD

**Issue by sachun78** [KimBono/ForNewJob#8]
https://developer.android.com/courses/pathways/jetpack-compose-for-android-developers-1?hl=ko

4. 첫 번째 Compose 앱 만들기
 - CodeLab 따라하기

**Comment by KimBono** [comment]
CodeLab ~ 7장 :  e92b306273231cc3097c33a62d6e7e81cece5197

**Comment by KimBono** [comment]
CodeLab ~9장 : 907a9f3ca47b207bbf61cb28a1fd1f9eb32e7265

**Comment by sachun78** [comment]
야 이눔아 빨리 빨리 끝내
